# Generated by Django 2.2.24 on 2021-10-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211026_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visiting',
            field=models.PositiveIntegerField(default=0, verbose_name='VistTimes'),
        ),
    ]
