# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-10-27 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_visiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='visiting',
        ),
        migrations.AddField(
            model_name='post',
            name='visit',
            field=models.PositiveIntegerField(default=0, verbose_name='Visit'),
        ),
    ]
