# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-28 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211027_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visit',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Visit'),
        ),
    ]
